{"name": "run a simple test false", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/christian/anaconda3/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/christian/anaconda3/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/demo.py\", line 13, in step_impl\n    assert context.failed is False\n"}, "steps": [{"name": "Given we have behave installed", "status": "passed", "start": 1599225866040, "stop": 1599225866040}, {"name": "When we implement a test", "status": "passed", "start": 1599225866040, "stop": 1599225866040}, {"name": "Then behave will test it for us as false!", "status": "failed", "statusDetails": {"message": "AssertionError\n", "trace": "  File \"/home/christian/anaconda3/lib/python3.8/site-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/home/christian/anaconda3/lib/python3.8/site-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features/steps/demo.py\", line 13, in step_impl\n    assert context.failed is False\n"}, "start": 1599225866040, "stop": 1599225866040}], "start": 1599225866039, "stop": 1599225866041, "uuid": "bd6c460d-7d75-4df4-81be-d618c57a190d", "historyId": "fa98337eb57abb91944e220ca09c40b1", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "showing off behave"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}